
drop table user;
create table user (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101),
	username varchar(30),
	name varchar(100),
	create_date timestamp,
	update_date timestamp
);

drop table user_group;
create table user_group (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101),
	name varchar(30)
);

drop table user_group_item;
create table user_group_item (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 101),
	group_id bigint,
	user_id bigint
);

/*
create sequence user_seq;
insert into user values (next value for user_seq, 'user1')
insert into user (identity(), 'user1');
select identity() from user;
*/