--create sequence user_seq;
--insert into user values (next value for user_seq, 'user1')

drop table user;
create table user (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	username varchar(30)
);
/*
insert into user (identity(), 'user1');
select identity() from user;
*/